name: Elixir CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    env:
      MIX_ENV: test
      # AFRICASTALKING_API: 6f2a021cbd7b2b0f5e9ba324f42dbf42403ab9a239d1c55c5a68cf54922bda77

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.9.4' # Define the elixir version [required]
        otp-version: '22.2' # Define the OTP version [required]
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Formatting 
      run: mix format --check-formatted
    - name: Run Tests
      run: mix test
